#!/usr/bin/env bash

# batteryhealthchargingctl - This script for setting charging limit
#
# This file is part of the gnome-shell extension Battery-Health-Charging@maniacx.github.com.

BAT0_END_PATH='/sys/class/power_supply/BAT0/charge_control_end_threshold'
BAT0_START_PATH='/sys/class/power_supply/BAT0/charge_control_start_threshold'
BAT1_END_PATH='/sys/class/power_supply/BAT1/charge_control_end_threshold'
BAT1_START_PATH='/sys/class/power_supply/BAT1/charge_control_start_threshold'
LG_PATH='/sys/devices/platform/lg-laptop/battery_care_limit'
LENOVO_PATH='/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode'
SONY_PATH='/sys/devices/platform/sony-laptop/battery_care_limiter'
SONY_HIGHSPEED_CHARGING_PATH='/sys/devices/platform/sony-laptop/battery_highspeed_charging'
HUAWEI_PATH='/sys/devices/platform/huawei-wmi/charge_control_thresholds'
SAMSUNG_PATH='/sys/devices/platform/samsung/battery_life_extender'
ACER_PATH='/sys/bus/wmi/drivers/acer-wmi-battery/health_mode'
BATC_END_PATH='/sys/class/power_supply/BATC/charge_control_end_threshold'
BATT_END_PATH='/sys/class/power_supply/BATT/charge_control_end_threshold'
TP_BAT0_END='/sys/devices/platform/smapi/BAT0/stop_charge_thresh'
TP_BAT0_START='/sys/devices/platform/smapi/BAT0/start_charge_thresh'
TP_BAT1_END='/sys/devices/platform/smapi/BAT1/stop_charge_thresh'
TP_BAT1_START='/sys/devices/platform/smapi/BAT1/start_charge_thresh'
PANASONIC_PATH='/sys/devices/platform/panasonic/eco_mode'
ASAHI_END_PATH='/sys/class/power_supply/macsmc-battery/charge_control_end_threshold'
ASAHI_START_PATH='/sys/class/power_supply/macsmc-battery/charge_control_start_threshold'
TUXEDO_PATH='/sys/devices/platform/tuxedo_keyboard/charging_profile/charging_profile'
GIGABYTE_MODE='/sys/devices/platform/gigabyte_laptop/charge_mode'
GIGABYTE_LIMIT='/sys/devices/platform/gigabyte_laptop/charge_limit'
APPLE_CHARGING_LED_PATH='/sys/class/power_supply/BAT0/charge_control_full_threshold'
BAT0_FORCE_DISCHARGE_PATH='/sys/class/power_supply/BAT0/charge_behaviour'
BAT1_FORCE_DISCHARGE_PATH='/sys/class/power_supply/BAT1/charge_behaviour'
DELL_SMBIOS_PATH='/usr/sbin/smbios-battery-ctl'
DELL_CCTK_PATH='/opt/dell/dcc/cctk'
CMB0_END_PATH='/sys/class/power_supply/CMB0/charge_control_end_threshold'
CMB1_END_PATH='/sys/class/power_supply/CMB1/charge_control_end_threshold'

EXTENSION_NAME="Battery Health Charging"
ACTION_BASE="dem.batteryhealthcharging"
RULE_BASE="$ACTION_BASE.setthreshold"
BHC_BASE="batteryhealthchargingctl"
BHC_DIR="/usr/local/bin"
RULE_DIR="/etc/polkit-1/rules.d"
LEGACY_POLKIT=false

COMMAND1_EXIT_STATUS=0
COMMAND2_EXIT_STATUS=0

EXIT_SUCCESS=0
EXIT_ERROR=1
EXIT_NEEDS_UPDATE=2

TOOLCMD=$1
ARG1=${2:-0}
ARG2=${3:-0}
ARG3=${4:-0}

source /etc/profile
test -r "$HOME/.profile" && source "$HOME/.profile"

function exit_modifier() {
    if [ "$1" -eq 0 ] && [ "$2" -eq 0 ]; then
        exit ${EXIT_SUCCESS}
    else
        exit ${EXIT_ERROR}
    fi
}

case "$TOOLCMD" in
    BAT0_END)
        echo "$ARG1" > "$BAT0_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    BAT0_END_START)
        echo "$ARG1" > "$BAT0_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG2" > "$BAT0_START_PATH"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    BAT0_START_END)
        echo "$ARG2" > "$BAT0_START_PATH"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG1" > "$BAT0_END_PATH"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    BAT1_END)
        echo "$ARG1" > "$BAT1_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    BAT1_END_START)
        echo "$ARG1" > "$BAT1_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG2" > "$BAT1_START_PATH"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    BAT1_START_END)
        echo "$ARG2" > "$BAT1_START_PATH"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG1" > "$BAT1_END_PATH"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    LG)
        echo "$ARG1" > "$LG_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    LENOVO)
        echo "$ARG1" > "$LENOVO_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    SONY)
        if [ "$ARG2" == "on" ];then
            echo "1" > "$SONY_HIGHSPEED_CHARGING_PATH"
            COMMAND1_EXIT_STATUS="$?"
        elif [ "$ARG2" == "off" ];then
            echo "0" > "$SONY_HIGHSPEED_CHARGING_PATH"
            COMMAND1_EXIT_STATUS="$?"
        fi
        echo "$ARG1" > "$SONY_PATH"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    HUAWEI)
        echo "$ARG2 $ARG1" > "$HUAWEI_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    SAMSUNG)
        echo "$ARG1" > "$SAMSUNG_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    ACER)
        echo "$ARG1" > "$ACER_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    PANASONIC)
        echo "$ARG1" > "$PANASONIC_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    BATC_END)
        echo "$ARG1" > "$BATC_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    BATT_END)
        echo "$ARG1" > "$BATT_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    TP_BAT0_END_START)
        echo "$ARG1" > "$TP_BAT0_END"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG2" > "$TP_BAT0_START"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    TP_BAT0_START_END)
        echo "$ARG2" > "$TP_BAT0_START"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG1" > "$TP_BAT0_END"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    TP_BAT1_END_START)
        echo "$ARG1" > "$TP_BAT1_END"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG2" > "$TP_BAT1_START"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    TP_BAT1_START_END)
        echo "$ARG2" > "$TP_BAT1_START"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG1" > "$TP_BAT1_END"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    ASAHI_END_START)
        echo "$ARG1" > "$ASAHI_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        echo "$ARG2" > "$ASAHI_START_PATH"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    TUXEDO)
        echo "$ARG1" > "$TUXEDO_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    GIGABYTE_THRESHOLD)
        if [ "$ARG1" = "true" ];then
            echo "1" > "$GIGABYTE_MODE"
            COMMAND1_EXIT_STATUS="$?"
        fi
        echo "$ARG2" > "$GIGABYTE_LIMIT"
        COMMAND2_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_ABSOLUTE_SMBIOS_BAT_READ)
        "$DELL_SMBIOS_PATH" --get-charging-cfg
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_ABSOLUTE_SMBIOS_BAT_WRITE)
        if [ "$ARG1" = "adv" ];then
            "$DELL_SMBIOS_PATH" --set-charging-mode='adaptive'
            COMMAND1_EXIT_STATUS="$?"
        elif [ "$ARG1" = "exp" ];then
            "$DELL_SMBIOS_PATH" --set-charging-mode='express'
            COMMAND1_EXIT_STATUS="$?"
        else
            "$DELL_SMBIOS_PATH" --set-charging-mode='custom'
            COMMAND1_EXIT_STATUS="$?"
            "$DELL_SMBIOS_PATH" --set-custom-charge-interval="$ARG2" "$ARG1"
            COMMAND2_EXIT_STATUS="$?"
        fi
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_ABSOLUTE_CCTK_BAT_READ)
        "$DELL_CCTK_PATH" --PrimaryBattChargeCfg
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_ABSOLUTE_CCTK_BAT_WRITE)
        if [ "$ARG1" = "adv" ];then
            "$DELL_CCTK_PATH" --PrimaryBattChargeCfg=Adaptive
            COMMAND1_EXIT_STATUS="$?"
        elif [ "$ARG1" = "exp" ];then
            "$DELL_CCTK_PATH" --PrimaryBattChargeCfg=Express
            COMMAND1_EXIT_STATUS="$?"
        else
            "$DELL_CCTK_PATH" --PrimaryBattChargeCfg=Custom:"$ARG2"-"$ARG1"
            COMMAND1_EXIT_STATUS="$?"
        fi
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_ABSOLUTE_CCTK_PASSWORD_BAT_WRITE)
        if [ "$ARG1" = "adv" ];then
            "$DELL_CCTK_PATH" --ValSetupPwd="$ARG3" --PrimaryBattChargeCfg=Adaptive
            COMMAND1_EXIT_STATUS="$?"
        elif [ "$ARG1" = "exp" ];then
            "$DELL_CCTK_PATH" --ValSetupPwd="$ARG3" --PrimaryBattChargeCfg=Express
            COMMAND1_EXIT_STATUS="$?"
        else
            "$DELL_CCTK_PATH" --ValSetupPwd="$ARG3" --PrimaryBattChargeCfg=Custom:"$ARG2"-"$ARG1"
            COMMAND1_EXIT_STATUS="$?"
        fi
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    APPLE)
        echo "$ARG1" > "$BAT0_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        if [ "$ARG2" -ne 0 ];then
            echo "$ARG2" > "$APPLE_CHARGING_LED_PATH"
            COMMAND2_EXIT_STATUS="$?"
        fi
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    FORCE_DISCHARGE_BAT0)
        echo "$ARG1" > "$BAT0_FORCE_DISCHARGE_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    FORCE_DISCHARGE_BAT1)
        echo "$ARG1" > "$BAT1_FORCE_DISCHARGE_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_RELATIVE_SMBIOS_BAT_READ)
        smbios-battery-ctl --get-charging-cfg
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_RELATIVE_SMBIOS_BAT_WRITE)
        if [ "$ARG1" = "adv" ];then
            smbios-battery-ctl --set-charging-mode='adaptive'
            COMMAND1_EXIT_STATUS="$?"
        elif [ "$ARG1" = "exp" ];then
            smbios-battery-ctl --set-charging-mode='express'
            COMMAND1_EXIT_STATUS="$?"
        else
            smbios-battery-ctl --set-charging-mode='custom'
            COMMAND1_EXIT_STATUS="$?"
            smbios-battery-ctl --set-custom-charge-interval="$ARG2" "$ARG1"
            COMMAND2_EXIT_STATUS="$?"
        fi
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_RELATIVE_CCTK_BAT_READ)
        cctk --PrimaryBattChargeCfg
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_RELATIVE_CCTK_BAT_WRITE)
        if [ "$ARG1" = "adv" ];then
            cctk --PrimaryBattChargeCfg=Adaptive
            COMMAND1_EXIT_STATUS="$?"
        elif [ "$ARG1" = "exp" ];then
            cctk --PrimaryBattChargeCfg=Express
            COMMAND1_EXIT_STATUS="$?"
        else
            cctk --PrimaryBattChargeCfg=Custom:"$ARG2"-"$ARG1"
            COMMAND1_EXIT_STATUS="$?"
        fi
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    DELL_RELATIVE_CCTK_PASSWORD_BAT_WRITE)
        if [ "$ARG1" = "adv" ];then
            cctk --ValSetupPwd="$ARG3" --PrimaryBattChargeCfg=Adaptive
            COMMAND1_EXIT_STATUS="$?"
        elif [ "$ARG1" = "exp" ];then
            cctk --ValSetupPwd="$ARG3" --PrimaryBattChargeCfg=Express
            COMMAND1_EXIT_STATUS="$?"
        else
            cctk --ValSetupPwd="$ARG3" --PrimaryBattChargeCfg=Custom:"$ARG2"-"$ARG1"
            COMMAND1_EXIT_STATUS="$?"
        fi
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    CMB0_END)
        echo "$ARG1" > "$CMB0_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    CMB1_END)
        echo "$ARG1" > "$CMB1_END_PATH"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
    FRAMEWORK_TOOL_THRESHOLD_READ)
        framework_tool --driver "$ARG1" --charge-limit
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    FRAMEWORK_TOOL_THRESHOLD_WRITE)
        framework_tool --driver "$ARG1" --charge-limit "$ARG2"
        COMMAND1_EXIT_STATUS="$?"
        exit_modifier "$COMMAND1_EXIT_STATUS" "$COMMAND2_EXIT_STATUS"
        ;;
    CHECKINSTALLATION)
        printf -v versions '%s\n%s' "$(pkaction --version | cut -d' ' -f3)" "0.106"
        if [[ $versions != "$(sort -V <<< "$versions")" ]];then
            LEGACY_POLKIT=false
        else
            LEGACY_POLKIT=true
        fi
        EXTDIR=$ARG1
        TOOL_USER=$ARG2
        RULE_IN="${EXTDIR}/10-${RULE_BASE}.rules"
        if [[ "$LEGACY_POLKIT" = true ]];then
            RULE_IN="${RULE_IN}.legacy"
            ACTION_IN="${EXTDIR}/${ACTION_BASE}.policy.in"
        fi
        TOOL_IN="${EXTDIR}/${BHC_BASE}"
        TOOL_OUT="${BHC_DIR}/${BHC_BASE}-${TOOL_USER}"
        RULE_OUT="${RULE_DIR}/10-${RULE_BASE}-${TOOL_USER}.rules"
        ACTION_ID="${RULE_BASE}.${TOOL_USER}"
        ACTION_OUT="/usr/share/polkit-1/actions/${ACTION_ID}.policy"

        if [[ "$LEGACY_POLKIT" = true ]];then
            echo "$EXTENSION_NAME: checking legacy rules and policies !"
            if ! sed -e "s:{{RULE_BASE}}:${RULE_BASE}:g" "${RULE_IN}" | \
                cmp --silent "${RULE_OUT}"
            then
                echo "$EXTENSION_NAME: installation needs to update rules !"
                exit ${EXIT_NEEDS_UPDATE}
            else
                if ! sed -e "s:{{PATH}}:${TOOL_OUT}:g" \
                    -e "s:{{ACTION_BASE}}:${ACTION_BASE}:g" \
                    -e "s:{{ACTION_ID}}:${ACTION_ID}:g" "${ACTION_IN}" | \
                    cmp --silent "${ACTION_OUT}"
                then
                    echo "$EXTENSION_NAME: installation needs to update policies!"
                    exit ${EXIT_NEEDS_UPDATE}
                fi
            fi
        else
            echo "$EXTENSION_NAME: checking rules !"
            if ! sed -e "s:{{TOOL_OUT}}:${TOOL_OUT}:g" \
                -e "s:{{TOOL_USER}}:${TOOL_USER}:g" "${RULE_IN}" | \
                cmp --silent "${RULE_OUT}"
            then
                echo "$EXTENSION_NAME: installation needs updating rules!"
                exit ${EXIT_NEEDS_UPDATE}
            fi
        fi
        echo "$EXTENSION_NAME: checking ctl !"
        if ! cmp --silent "${TOOL_IN}" "${TOOL_OUT}";then
            echo "$EXTENSION_NAME: installation needs updating ctl!"
            exit ${EXIT_NEEDS_UPDATE}
        fi
        echo "$EXTENSION_NAME: installation is up to date "
        exit ${EXIT_SUCCESS}
        ;;
    *)
        echo "Unknown" >&2
esac

